<?php
/**
 * Simple Database Export Script
 * Use this when mysqldump is not available in the container.
 * 
 * Usage from Host:
 * docker exec shift_scheduler php /var/www/html/db_export.php > database.sql
 */

require_once __DIR__ . '/config/database.php';

try {
    $db = Database::getInstance()->getConnection();

    // Get all tables
    $tables = [];
    $stmt = $db->query("SHOW TABLES");
    while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
        $tables[] = $row[0];
    }

    echo "-- Shift Scheduler Database Dump\n";
    echo "-- Generated by db_export.php\n";
    echo "-- Date: " . date('Y-m-d H:i:s') . "\n\n";
    echo "SET FOREIGN_KEY_CHECKS=0;\n";
    echo "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
    echo "START TRANSACTION;\n";
    echo "SET time_zone = \"+00:00\";\n\n";

    foreach ($tables as $table) {
        echo "-- Structure for table `$table`\n";
        echo "DROP TABLE IF EXISTS `$table`;\n";

        $row = $db->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_ASSOC);
        echo $row['Create Table'] . ";\n\n"; // Different PDO drivers might return keys with different cases, usually 'Create Table'

        echo "-- Dumping data for table `$table`\n";
        $rows = $db->query("SELECT * FROM `$table`");
        $rows->setFetchMode(PDO::FETCH_ASSOC);

        foreach ($rows as $row) {
            $fields = array_map(function ($value) use ($db) {
                if ($value === null)
                    return "NULL";
                return $db->quote($value);
            }, $row);

            $values = implode(", ", $fields);
            $cols = implode("`, `", array_keys($row));

            echo "INSERT INTO `$table` (`$cols`) VALUES ($values);\n";
        }
        echo "\n";
    }

    echo "SET FOREIGN_KEY_CHECKS=1;\n";
    echo "COMMIT;\n";

} catch (Exception $e) {
    fwrite(STDERR, "Error exporting database: " . $e->getMessage() . "\n");
    exit(1);
}
